[connections.weaviate]
url = "<>" #Weaviate cluster url
authorization = "Bearer <token>" # Bearer token to authorize weaviate cluster
api_key = "<apiKey>" # Weaviate api key to authorize weaviate cluster(Provide either authorization or api_key
class = "<class name>" #Class name in weaviate cluster to retrieve data.
